use vstd::prelude::*;
use crate::symbol::*;
use crate::word::*;
use crate::presentation::*;
use crate::presentation_lemmas::*;
use crate::free_product::*;
use crate::quotient::*;

verus! {

//  ============================================================
//  Amalgamated Free Products
//  ============================================================
//
//  Given two presentations G₁ = ⟨S₁ | R₁⟩ and G₂ = ⟨S₂ | R₂⟩,
//  and identification pairs (u_i, v_i) where u_i is a word in G₁
//  and v_i is a word in G₂, the amalgamated free product is:
//
//    G₁ *_A G₂ = ⟨S₁ ∪ S₂ | R₁ ∪ R₂ ∪ { u_i · shift(v_i)⁻¹ }⟩
//
//  This identifies the subgroup generated by the u_i in G₁ with
//  the subgroup generated by the v_i in G₂.

///  Data for an amalgamated free product.
///
///  - `p1`, `p2`: the two presentations being amalgamated
///  - `identifications`: pairs (u_i, v_i) where u_i is a word in G₁,
///    v_i is a word in G₂. These are identified in the amalgamation.
pub struct AmalgamatedData {
    pub p1: Presentation,
    pub p2: Presentation,
    pub identifications: Seq<(Word, Word)>,
}

///  The amalgamation data is valid:
///  - Both presentations are valid
///  - Each u_i is word_valid for p1
///  - Each v_i is word_valid for p2
pub open spec fn amalgamated_data_valid(data: AmalgamatedData) -> bool {
    presentation_valid(data.p1)
    && presentation_valid(data.p2)
    && forall|i: int| 0 <= i < data.identifications.len() ==>
        word_valid(data.identifications[i].0, data.p1.num_generators)
        && word_valid(data.identifications[i].1, data.p2.num_generators)
}

///  Build the i-th identification relator: u_i · shift(v_i)⁻¹.
///
///  In the free product, p2's generators are shifted by p1.num_generators.
///  So we form the word u_i · inverse(shift(v_i, p1.num_generators)).
pub open spec fn amalgamation_relator(data: AmalgamatedData, i: int) -> Word
    recommends
        0 <= i < data.identifications.len(),
{
    let (u_i, v_i) = data.identifications[i];
    let shifted_v = shift_word(v_i, data.p1.num_generators);
    concat(u_i, inverse_word(shifted_v))
}

///  Build all identification relators.
pub open spec fn amalgamation_relators(data: AmalgamatedData) -> Seq<Word> {
    Seq::new(data.identifications.len(), |i: int| amalgamation_relator(data, i))
}

///  The amalgamated free product: free_product(p1, p2) with identification relators added.
pub open spec fn amalgamated_free_product(data: AmalgamatedData) -> Presentation {
    add_relators(free_product(data.p1, data.p2), amalgamation_relators(data))
}

//  ============================================================
//  Helper: add_relators preserves num_generators
//  ============================================================

///  Adding relators preserves the number of generators.
pub proof fn lemma_add_relators_num_generators(p: Presentation, rs: Seq<Word>)
    ensures
        add_relators(p, rs).num_generators == p.num_generators,
    decreases rs.len(),
{
    if rs.len() == 0 {
    } else {
        let p1 = add_relator(p, rs.first());
        assert(p1.num_generators == p.num_generators);
        lemma_add_relators_num_generators(p1, rs.drop_first());
    }
}

//  ============================================================
//  Validity
//  ============================================================

///  Shifted word validity: if w is word_valid for p2, then shift_word(w, p1.num_generators)
///  is word_valid for free_product(p1, p2).
proof fn lemma_shift_word_valid(w: Word, p1: Presentation, p2: Presentation)
    requires
        word_valid(w, p2.num_generators),
    ensures
        word_valid(shift_word(w, p1.num_generators), p1.num_generators + p2.num_generators),
{
    let offset = p1.num_generators;
    let n = p1.num_generators + p2.num_generators;
    let sw = shift_word(w, offset);
    assert forall|k: int| 0 <= k < sw.len()
        implies symbol_valid(#[trigger] sw[k], n)
    by {
        assert(sw[k] == shift_symbol(w[k], offset));
        assert(symbol_valid(w[k], p2.num_generators));
        //  shift_symbol maps Gen(i) → Gen(i+offset), Inv(i) → Inv(i+offset)
        //  If i < p2.num_generators, then i+offset < p2.num_generators+offset = n
    }
}

///  Each amalgamation relator is word_valid for the free product.
proof fn lemma_amalgamation_relator_valid(data: AmalgamatedData, i: int)
    requires
        amalgamated_data_valid(data),
        0 <= i < data.identifications.len(),
    ensures
        word_valid(
            amalgamation_relator(data, i),
            free_product(data.p1, data.p2).num_generators,
        ),
{
    let (u_i, v_i) = data.identifications[i];
    let fp = free_product(data.p1, data.p2);
    let n = fp.num_generators;

    //  u_i is word_valid for p1.num_generators < n
    assert(word_valid(u_i, n)) by {
        assert forall|k: int| 0 <= k < u_i.len()
            implies symbol_valid(#[trigger] u_i[k], n)
        by {
            assert(symbol_valid(u_i[k], data.p1.num_generators));
        }
    }

    //  shift(v_i) is word_valid for n
    lemma_shift_word_valid(v_i, data.p1, data.p2);
    let shifted_v = shift_word(v_i, data.p1.num_generators);

    //  inverse(shift(v_i)) is word_valid for n
    lemma_inverse_word_valid(shifted_v, n);

    //  concat is word_valid
    lemma_concat_word_valid(u_i, inverse_word(shifted_v), n);
}

///  The amalgamated free product is a valid presentation.
pub proof fn lemma_amalgamated_valid(data: AmalgamatedData)
    requires
        amalgamated_data_valid(data),
    ensures
        presentation_valid(amalgamated_free_product(data)),
{
    let fp = free_product(data.p1, data.p2);
    let rels = amalgamation_relators(data);

    //  fp is presentation_valid
    reveal(presentation_valid);
    assert(presentation_valid(fp)) by {
        assert forall|k: int| 0 <= k < fp.relators.len()
            implies word_valid(fp.relators[k], fp.num_generators)
        by {
            if k < data.p1.relators.len() as int {
                assert(fp.relators[k] == data.p1.relators[k]);
                assert(word_valid(data.p1.relators[k], data.p1.num_generators));
                assert forall|m: int| 0 <= m < fp.relators[k].len()
                    implies symbol_valid(fp.relators[k][m], fp.num_generators)
                by {
                    assert(symbol_valid(fp.relators[k][m], data.p1.num_generators));
                }
            } else {
                let j = k - data.p1.relators.len() as int;
                assert(fp.relators[k] == shift_word(data.p2.relators[j], data.p1.num_generators));
                let w = data.p2.relators[j];
                assert(word_valid(w, data.p2.num_generators));
                lemma_shift_word_valid(w, data.p1, data.p2);
            }
        }
    }

    //  Each amalgamation relator is word_valid for fp
    assert forall|k: int| 0 <= k < rels.len()
        implies word_valid(rels[k], fp.num_generators)
    by {
        assert(rels[k] == amalgamation_relator(data, k));
        lemma_amalgamation_relator_valid(data, k);
    }

    lemma_add_relators_valid(fp, rels);
}

//  ============================================================
//  Left Embedding
//  ============================================================

///  Left embedding: equivalence in p1 implies equivalence in the amalgamated product.
pub proof fn lemma_left_embeds_in_amalgamation(
    data: AmalgamatedData,
    w1: Word, w2: Word,
)
    requires
        equiv_in_presentation(data.p1, w1, w2),
    ensures
        equiv_in_presentation(amalgamated_free_product(data), w1, w2),
{
    //  p1 words embed in free_product(p1, p2)
    lemma_left_embeds(data.p1, data.p2, w1, w2);
    //  free product embeds in amalgamation (adding relators preserves equiv)
    lemma_add_relators_preserves_equiv(
        free_product(data.p1, data.p2),
        amalgamation_relators(data),
        w1, w2,
    );
}

//  ============================================================
//  Right Embedding
//  ============================================================

///  Right embedding: equivalence in p2 implies equivalence of shifted words
///  in the amalgamated product.
pub proof fn lemma_right_embeds_in_amalgamation(
    data: AmalgamatedData,
    w1: Word, w2: Word,
)
    requires
        equiv_in_presentation(data.p2, w1, w2),
    ensures
        equiv_in_presentation(
            amalgamated_free_product(data),
            shift_word(w1, data.p1.num_generators),
            shift_word(w2, data.p1.num_generators),
        ),
{
    //  p2 words embed in free product via shifting
    lemma_right_embeds(data.p1, data.p2, w1, w2);
    //  free product embeds in amalgamation
    lemma_add_relators_preserves_equiv(
        free_product(data.p1, data.p2),
        amalgamation_relators(data),
        shift_word(w1, data.p1.num_generators),
        shift_word(w2, data.p1.num_generators),
    );
}

//  ============================================================
//  Identification
//  ============================================================

///  The identified words are equivalent in the amalgamated product:
///  u_i ≡ shift(v_i) in the amalgamated free product.
///
///  Proof: u_i · inverse(shift(v_i)) is a relator, so it equals ε.
///  Then u_i ≡ u_i · ε ≡ u_i · (inverse(shift(v_i)) · shift(v_i))
///          ≡ (u_i · inverse(shift(v_i))) · shift(v_i) ≡ ε · shift(v_i) ≡ shift(v_i).
pub proof fn lemma_amalgamation_identifies(data: AmalgamatedData, i: int)
    requires
        amalgamated_data_valid(data),
        0 <= i < data.identifications.len(),
    ensures
        equiv_in_presentation(
            amalgamated_free_product(data),
            data.identifications[i].0,
            shift_word(data.identifications[i].1, data.p1.num_generators),
        ),
{
    let afp = amalgamated_free_product(data);
    let (u_i, v_i) = data.identifications[i];
    let shifted_v = shift_word(v_i, data.p1.num_generators);
    let rel = amalgamation_relator(data, i);
    let rels = amalgamation_relators(data);

    //  rel = concat(u_i, inverse_word(shifted_v))
    assert(rel == concat(u_i, inverse_word(shifted_v)));

    //  rel is the i-th amalgamation relator → it equals ε in afp
    assert(rels[i] == rel);
    lemma_each_added_relator_is_identity(
        free_product(data.p1, data.p2),
        rels,
        i,
    );
    //  rel ≡ ε in afp

    //  Now derive: u_i ≡ shifted_v
    //  Strategy: rel ≡ ε, and rel = u_i · inv(shifted_v)
    //  So u_i · inv(shifted_v) ≡ ε
    //  u_i · inv(shifted_v) · shifted_v ≡ ε · shifted_v ≡ shifted_v
    //  u_i · (inv(shifted_v) · shifted_v) ≡ shifted_v  (by assoc)
    //  u_i · ε ≡ shifted_v  (since inv(w) · w ≡ ε)
    //  u_i ≡ shifted_v

    //  Step 1: rel ≡ ε
    //  (already established above)

    //  Step 2: concat(rel, shifted_v) ≡ concat(ε, shifted_v) ≡ shifted_v
    lemma_equiv_concat_left(afp, rel, empty_word(), shifted_v);
    assert(concat(empty_word(), shifted_v) =~= shifted_v);
    lemma_equiv_refl(afp, shifted_v);
    lemma_equiv_transitive(afp, concat(rel, shifted_v), concat(empty_word(), shifted_v), shifted_v);

    //  Step 3: concat(rel, shifted_v) =~= concat(u_i, concat(inv(shifted_v), shifted_v))
    assert(concat(rel, shifted_v) =~= concat(u_i, concat(inverse_word(shifted_v), shifted_v)));

    //  Step 4: inv(shifted_v) · shifted_v ≡ ε
    lemma_word_inverse_left(afp, shifted_v);

    //  Step 5: u_i · (inv(shifted_v) · shifted_v) ≡ u_i · ε
    lemma_equiv_concat_right(afp, u_i, concat(inverse_word(shifted_v), shifted_v), empty_word());

    //  Step 6: u_i · ε =~= u_i
    assert(concat(u_i, empty_word()) =~= u_i);
    lemma_equiv_refl(afp, u_i);

    //  Step 7: Chain: u_i · (inv(shifted_v) · shifted_v) ≡ u_i · ε ≡ u_i
    lemma_equiv_transitive(
        afp,
        concat(u_i, concat(inverse_word(shifted_v), shifted_v)),
        concat(u_i, empty_word()),
        u_i,
    );

    //  Now we have:
    //    concat(rel, shifted_v) ≡ shifted_v  (from step 2)
    //    concat(u_i, concat(inv(shifted_v), shifted_v)) ≡ u_i  (from step 7)
    //  And these LHS are extensionally equal (step 3).

    //  So: u_i ≡ concat(rel, shifted_v) ≡ shifted_v
    //  Need: u_i ≡ shifted_v

    //  We need symmetry for the chain. Let's use word_valid + presentation_valid.
    lemma_amalgamated_valid(data);
    let fp = free_product(data.p1, data.p2);
    let n = afp.num_generators;

    //  afp.num_generators == fp.num_generators
    lemma_add_relators_num_generators(fp, rels);
    assert(n == fp.num_generators);

    //  word_valid(u_i, n)
    assert(word_valid(u_i, n)) by {
        assert forall|k: int| 0 <= k < u_i.len()
            implies symbol_valid(#[trigger] u_i[k], n)
        by {
            assert(symbol_valid(u_i[k], data.p1.num_generators));
        }
    }

    //  word_valid(shifted_v, n)
    lemma_shift_word_valid(v_i, data.p1, data.p2);
    assert(word_valid(shifted_v, n));

    //  word_valid(inv(shifted_v), n)
    lemma_inverse_word_valid(shifted_v, n);

    //  word_valid(concat(inv(sv), sv), n)
    lemma_concat_word_valid(inverse_word(shifted_v), shifted_v, n);

    //  word_valid(concat(u_i, concat(inv(sv), sv)), n)
    lemma_concat_word_valid(u_i, concat(inverse_word(shifted_v), shifted_v), n);

    //  u_i ≡ concat(u_i, concat(inv(sv), sv)) (symmetric)
    lemma_equiv_symmetric(
        afp,
        concat(u_i, concat(inverse_word(shifted_v), shifted_v)),
        u_i,
    );

    //  Chain: u_i ≡ concat(u_i, concat(inv(sv), sv)) = concat(rel, sv) ≡ shifted_v
    lemma_equiv_transitive(
        afp,
        u_i,
        concat(u_i, concat(inverse_word(shifted_v), shifted_v)),
        shifted_v,
    );
}

//  ============================================================
//  Free product embeds in amalgamation
//  ============================================================

///  The free product embeds in the amalgamated free product:
///  equivalence in free_product(p1, p2) implies equivalence in the amalgamation.
pub proof fn lemma_free_product_embeds_in_amalgamation(
    data: AmalgamatedData,
    w1: Word, w2: Word,
)
    requires
        equiv_in_presentation(free_product(data.p1, data.p2), w1, w2),
    ensures
        equiv_in_presentation(amalgamated_free_product(data), w1, w2),
{
    lemma_add_relators_preserves_equiv(
        free_product(data.p1, data.p2),
        amalgamation_relators(data),
        w1, w2,
    );
}

} //  verus!
