use vstd::prelude::*;
use crate::symbol::*;
use crate::word::*;
use crate::presentation::*;
use crate::presentation_lemmas::*;
use crate::quotient::*;

verus! {

//  ============================================================
//  Benign Subgroups
//  ============================================================
//
//  A subgroup H of a group G is "benign" if G embeds in a
//  finitely presented group K such that H = G ∩ L for some
//  finitely generated subgroup L of K.
//
//  This is the key concept in Higman's embedding theorem:
//  a recursively presented group embeds in a finitely presented
//  group iff its relators form a benign subgroup of the free group.
//
//  We formalize this at the presentation level:
//  - G is a presented group
//  - The subgroup is specified by a set of generator words
//  - K is a finitely presented overgroup
//  - The embedding is an injective homomorphism G → K
//  - L is generated by finitely many words in K

//  ============================================================
//  Subgroup generated by words
//  ============================================================

///  A word is in the subgroup generated by `gens` if it is equivalent
///  (in presentation p) to some product of generators and their inverses.
///  Formally: the generated subgroup is the closure of gens ∪ gens⁻¹
///  under concatenation and equivalence.
///
///  We define membership inductively via "generator derivations":
///  a sequence of generator words (possibly inverted) whose
///  concatenation is equivalent to w.
pub open spec fn in_generated_subgroup(
    p: Presentation, gens: Seq<Word>, w: Word,
) -> bool {
    exists|factors: Seq<Word>|
        #[trigger] factors_from_generators(gens, factors) &&
        equiv_in_presentation(p, concat_all(factors), w)
}

///  A word is a generator or the inverse of a generator.
pub open spec fn is_generator_or_inverse(gens: Seq<Word>, w: Word) -> bool {
    exists|j: int| 0 <= j < gens.len() &&
        (w == #[trigger] gens[j] || w == inverse_word(gens[j]))
}

///  Each factor is either a generator or the inverse of a generator.
pub open spec fn factors_from_generators(gens: Seq<Word>, factors: Seq<Word>) -> bool {
    forall|k: int| #![trigger factors[k]]
        0 <= k < factors.len() ==>
        is_generator_or_inverse(gens, factors[k])
}

///  Concatenate a sequence of words: w₁ · w₂ · ... · wₙ.
pub open spec fn concat_all(ws: Seq<Word>) -> Word
    decreases ws.len(),
{
    if ws.len() == 0 {
        empty_word()
    } else {
        concat(ws.first(), concat_all(ws.drop_first()))
    }
}

//  ============================================================
//  Embedding application (self-contained, no HomomorphismData)
//  ============================================================

///  Apply an embedding (Seq<Word> of generator images) to a single symbol.
pub open spec fn apply_embedding_symbol(images: Seq<Word>, s: Symbol) -> Word {
    match s {
        Symbol::Gen(i) => images[i as int],
        Symbol::Inv(i) => inverse_word(images[i as int]),
    }
}

///  Apply an embedding to a word: replace each symbol with its image.
pub open spec fn apply_embedding(images: Seq<Word>, w: Word) -> Word
    decreases w.len(),
{
    if w.len() == 0 {
        empty_word()
    } else {
        concat(apply_embedding_symbol(images, w.first()), apply_embedding(images, w.drop_first()))
    }
}

//  ============================================================
//  Benign subgroup definition
//  ============================================================

///  Witness data for a benign subgroup.
pub struct BenignWitness {
    ///  The finitely presented overgroup K.
    pub overgroup: Presentation,
    ///  The embedding G → K (maps each generator i to a word in K).
    pub embedding: Seq<Word>,
    ///  Generators of the subgroup L ≤ K.
    pub l_generators: Seq<Word>,
}

///  The embedding is injective: equiv in K implies equiv in G.
pub open spec fn embedding_injective(
    g: Presentation, k: Presentation, emb: Seq<Word>,
) -> bool {
    emb.len() == g.num_generators &&
    (forall|w1: Word, w2: Word|
        word_valid(w1, g.num_generators) && word_valid(w2, g.num_generators) &&
        equiv_in_presentation(k, apply_embedding(emb,w1), apply_embedding(emb,w2))
        ==> #[trigger] equiv_in_presentation(g, w1, w2))
}

///  The embedding preserves equivalence: equiv in G implies equiv in K.
pub open spec fn embedding_preserving(
    g: Presentation, k: Presentation, emb: Seq<Word>,
) -> bool {
    emb.len() == g.num_generators &&
    (forall|w1: Word, w2: Word|
        word_valid(w1, g.num_generators) && word_valid(w2, g.num_generators) &&
        equiv_in_presentation(g, w1, w2)
        ==> #[trigger] equiv_in_presentation(k, apply_embedding(emb,w1), apply_embedding(emb,w2)))
}

///  A subgroup (specified by generators) of G is benign.
///
///  There exists a finitely presented K, an injective embedding G → K,
///  and finitely generated L ≤ K such that:
///    w ∈ ⟨gens⟩_G  iff  emb(w) ∈ ⟨l_generators⟩_K
///
///  This captures: the image of the subgroup = intersection of L with image of G.
pub open spec fn is_benign(
    g: Presentation, gens: Seq<Word>,
) -> bool {
    exists|w: BenignWitness| #[trigger] benign_witness_valid(g, gens, w)
}

///  A benign witness is valid.
pub open spec fn benign_witness_valid(
    g: Presentation, gens: Seq<Word>, w: BenignWitness,
) -> bool {
    //  K is finitely presented and valid
    &&& presentation_valid(w.overgroup)
    //  Embedding maps G's generators to valid K-words
    &&& w.embedding.len() == g.num_generators
    &&& (forall|i: int| 0 <= i < w.embedding.len() ==>
        word_valid(#[trigger] w.embedding[i], w.overgroup.num_generators))
    //  L generators are valid K-words
    &&& (forall|i: int| 0 <= i < w.l_generators.len() ==>
        word_valid(#[trigger] w.l_generators[i], w.overgroup.num_generators))
    //  Embedding is injective (K-equiv → G-equiv)
    &&& embedding_injective(g, w.overgroup, w.embedding)
    //  Embedding preserves equivalence (G-equiv → K-equiv)
    &&& embedding_preserving(g, w.overgroup, w.embedding)
    //  Forward: subgroup member → image is in L
    &&& (forall|v: Word|
        word_valid(v, g.num_generators) &&
        in_generated_subgroup(g, gens, v)
        ==> #[trigger] in_generated_subgroup(w.overgroup, w.l_generators, apply_embedding(w.embedding,v)))
    //  Backward: image in L → subgroup member
    &&& (forall|v: Word|
        word_valid(v, g.num_generators) &&
        in_generated_subgroup(w.overgroup, w.l_generators, apply_embedding(w.embedding,v))
        ==> #[trigger] in_generated_subgroup(g, gens, v))
    //  Quotient forward: equiv in G/⟨⟨gens⟩⟩ → equiv in K/⟨⟨l_gens⟩⟩ via embedding
    &&& (forall|w1: Word, w2: Word|
        word_valid(w1, g.num_generators) && word_valid(w2, g.num_generators) &&
        equiv_in_presentation(add_relators(g, gens), w1, w2)
        ==> #[trigger] equiv_in_presentation(
            add_relators(w.overgroup, w.l_generators),
            apply_embedding(w.embedding, w1),
            apply_embedding(w.embedding, w2)))
    //  Quotient backward: equiv in K/⟨⟨l_gens⟩⟩ via embedding → equiv in G/⟨⟨gens⟩⟩
    &&& (forall|w1: Word, w2: Word|
        word_valid(w1, g.num_generators) && word_valid(w2, g.num_generators) &&
        equiv_in_presentation(
            add_relators(w.overgroup, w.l_generators),
            apply_embedding(w.embedding, w1),
            apply_embedding(w.embedding, w2))
        ==> #[trigger] equiv_in_presentation(add_relators(g, gens), w1, w2))
}

//  ============================================================
//  Basic lemmas about concat_all
//  ============================================================

///  concat_all of empty is empty_word.
pub proof fn lemma_concat_all_empty()
    ensures
        concat_all(Seq::<Word>::empty()) == empty_word(),
{
}

///  concat_all of a singleton is the word itself (up to trailing ε).
pub proof fn lemma_concat_all_singleton(w: Word)
    ensures
        concat_all(seq![w]) =~= w,
{
    reveal_with_fuel(concat_all, 2);
    assert(seq![w].first() == w);
    assert(seq![w].drop_first() =~= Seq::<Word>::empty());
    assert(concat_all(Seq::<Word>::empty()) =~= empty_word());
    assert(concat(w, empty_word()) =~= w);
}

///  The identity word is in any generated subgroup.
pub proof fn lemma_identity_in_generated_subgroup(p: Presentation, gens: Seq<Word>)
    ensures
        in_generated_subgroup(p, gens, empty_word()),
{
    let factors = Seq::<Word>::empty();
    assert(factors_from_generators(gens, factors));
    assert(concat_all(factors) =~= empty_word());
    lemma_equiv_refl(p, empty_word());
}

///  Each generator is in the generated subgroup.
pub proof fn lemma_generator_in_generated_subgroup(
    p: Presentation, gens: Seq<Word>, i: int,
)
    requires
        0 <= i < gens.len(),
    ensures
        in_generated_subgroup(p, gens, gens[i]),
{
    let factors = seq![gens[i]];
    assert(factors_from_generators(gens, factors)) by {
        assert forall|k: int| 0 <= k < factors.len()
            implies is_generator_or_inverse(gens, #[trigger] factors[k])
        by {
            assert(factors[k] == gens[i]);
            assert(factors[k] == gens[i] || factors[k] == inverse_word(gens[i]));
        }
    }
    lemma_concat_all_singleton(gens[i]);
    lemma_equiv_refl(p, gens[i]);
}

///  apply_embedding preserves word_valid.
pub proof fn lemma_apply_embedding_valid(images: Seq<Word>, w: Word, n: nat)
    requires
        word_valid(w, images.len()),
        forall|i: int| 0 <= i < images.len() ==> word_valid(#[trigger] images[i], n),
    ensures
        word_valid(apply_embedding(images, w), n),
    decreases w.len(),
{
    if w.len() > 0 {
        let sym = w.first();
        let rest = w.drop_first();
        lemma_apply_embedding_valid(images, rest, n);
        match sym {
            Symbol::Inv(idx) => {
                lemma_inverse_word_valid(images[idx as int], n);
            },
            _ => {},
        }
        lemma_concat_word_valid(
            apply_embedding_symbol(images, sym),
            apply_embedding(images, rest),
            n,
        );
    }
}

///  apply_embedding commutes with inverse_word.
pub proof fn lemma_apply_embedding_inverse(images: Seq<Word>, w: Word)
    ensures
        apply_embedding(images, inverse_word(w))
            =~= inverse_word(apply_embedding(images, w)),
    decreases w.len(),
{
    if w.len() == 0 {
    } else {
        let rest = w.drop_first();
        lemma_apply_embedding_inverse(images, rest);
        lemma_apply_embedding_concat(images,
            inverse_word(rest), Seq::new(1, |_i: int| inverse_symbol(w.first())));
    }
}

///  apply_embedding distributes over concat.
pub proof fn lemma_apply_embedding_concat(images: Seq<Word>, w1: Word, w2: Word)
    ensures
        apply_embedding(images, concat(w1, w2))
            =~= concat(apply_embedding(images, w1), apply_embedding(images, w2)),
    decreases w1.len(),
{
    if w1.len() == 0 {
        assert(concat(w1, w2) =~= w2);
    } else {
        let w1_rest = w1.drop_first();
        lemma_apply_embedding_concat(images, w1_rest, w2);
        //  Z3 should unfold apply_embedding and see the mapped seqs match.
    }
}

} //  verus!
