use vstd::prelude::*;
use crate::symbol::*;
use crate::word::*;
use crate::presentation::*;
use crate::presentation_lemmas::*;
use crate::benign::*;

verus! {

//  ============================================================
//  HNN Extensions
//  ============================================================
//
//  Given a base group G = ⟨S | R⟩ and pairs of associated words (a_i, b_i),
//  the HNN extension is:
//    G*_φ = ⟨S, t | R, t⁻¹·a_i·t·b_i⁻¹ for each i⟩
//
//  The stable letter t is Gen(|S|), the new generator.

///  Data for an HNN extension: base presentation plus association pairs.
pub struct HNNData {
    pub base: Presentation,
    ///  Each pair (a_i, b_i) represents the relation t⁻¹·a_i·t = b_i.
    pub associations: Seq<(Word, Word)>,
}

///  The stable letter symbol: Gen(base.num_generators).
pub open spec fn stable_letter(data: HNNData) -> Symbol {
    Symbol::Gen(data.base.num_generators)
}

///  The inverse of the stable letter.
pub open spec fn stable_letter_inv(data: HNNData) -> Symbol {
    Symbol::Inv(data.base.num_generators)
}

///  Build the i-th HNN relator: t⁻¹ · a_i · t · b_i⁻¹.
pub open spec fn hnn_relator(data: HNNData, i: int) -> Word
    recommends
        0 <= i < data.associations.len(),
{
    let (a_i, b_i) = data.associations[i];
    let t = stable_letter(data);
    let t_inv = stable_letter_inv(data);
    //  t⁻¹ · a_i · t · b_i⁻¹
    Seq::new(1, |_j: int| t_inv) + a_i + Seq::new(1, |_j: int| t) + inverse_word(b_i)
}

///  Build the sequence of all HNN relators.
pub open spec fn hnn_relators(data: HNNData) -> Seq<Word> {
    Seq::new(data.associations.len(), |i: int| hnn_relator(data, i))
}

///  An HNN extension is valid when the base is valid and all association words are word_valid.
pub open spec fn hnn_data_valid(data: HNNData) -> bool {
    presentation_valid(data.base)
    && forall|i: int| 0 <= i < data.associations.len() ==>
        word_valid(data.associations[i].0, data.base.num_generators)
        && word_valid(data.associations[i].1, data.base.num_generators)
}

///  The HNN associations define a valid isomorphism between the subgroups
///  generated by the a_i's and b_i's.
///
///  Formally: for any word w over |associations| generators, substituting
///  a_i for generator i gives identity in G iff substituting b_i for
///  generator i gives identity in G. This ensures the map a_i ↦ b_i
///  extends to a well-defined isomorphism of the generated subgroups.
///
///  This condition is required for Britton's Lemma. Without it, the
///  inclusion G → G* may not be injective. Counterexample: G = ⟨a | ⟩
///  with association (ε, a) satisfies hnn_data_valid but the HNN relator
///  t⁻¹t·a⁻¹ forces a ≡ ε in G* while a ≢ ε in G.
pub open spec fn hnn_associations_isomorphic(data: HNNData) -> bool {
    let k = data.associations.len();
    let a_words = Seq::new(k, |i: int| data.associations[i].0);
    let b_words = Seq::new(k, |i: int| data.associations[i].1);
    forall|w: Word| word_valid(w, k as nat) ==> (
        equiv_in_presentation(data.base, apply_embedding(a_words, w), empty_word())
        <==>
        equiv_in_presentation(data.base, apply_embedding(b_words, w), empty_word())
    )
}

///  The HNN presentation: base generators + t, base relators + HNN relators.
pub open spec fn hnn_presentation(data: HNNData) -> Presentation {
    Presentation {
        num_generators: data.base.num_generators + 1,
        relators: data.base.relators + hnn_relators(data),
    }
}

///  The HNN presentation extends the base presentation
///  (base relators come first, same plus one generator but apply_step ignores num_generators).
proof fn lemma_hnn_extends_base(data: HNNData)
    ensures ({
        let hp = hnn_presentation(data);
        let bp = data.base;
        &&& bp.relators.len() <= hp.relators.len()
        &&& hp.relators.subrange(0, bp.relators.len() as int) == bp.relators
    }),
{
    let hp = hnn_presentation(data);
    let bp = data.base;
    assert(hp.relators.subrange(0, bp.relators.len() as int) =~= bp.relators);
}

///  A derivation step valid in the base is valid in the HNN presentation.
proof fn lemma_step_valid_in_hnn(
    data: HNNData,
    w: Word, step: DerivationStep, w_prime: Word,
)
    requires
        apply_step(data.base, w, step) == Some(w_prime),
    ensures
        apply_step(hnn_presentation(data), w, step) == Some(w_prime),
{
    let hp = hnn_presentation(data);
    let bp = data.base;
    match step {
        DerivationStep::FreeReduce { position } => {},
        DerivationStep::FreeExpand { position, symbol } => {},
        DerivationStep::RelatorInsert { position, relator_index, inverted } => {
            assert(0 <= relator_index < bp.relators.len());
            assert(hp.relators[relator_index as int] == bp.relators[relator_index as int]);
            assert(get_relator(hp, relator_index, inverted) == get_relator(bp, relator_index, inverted));
        },
        DerivationStep::RelatorDelete { position, relator_index, inverted } => {
            assert(0 <= relator_index < bp.relators.len());
            assert(hp.relators[relator_index as int] == bp.relators[relator_index as int]);
            assert(get_relator(hp, relator_index, inverted) == get_relator(bp, relator_index, inverted));
        },
    }
}

///  A derivation valid in the base is valid in the HNN presentation.
pub proof fn lemma_derivation_valid_in_hnn(
    data: HNNData,
    steps: Seq<DerivationStep>, w1: Word, w2: Word,
)
    requires
        derivation_produces(data.base, steps, w1) == Some(w2),
    ensures
        derivation_produces(hnn_presentation(data), steps, w1) == Some(w2),
    decreases steps.len(),
{
    if steps.len() == 0 {
    } else {
        let step = steps.first();
        let next = apply_step(data.base, w1, step).unwrap();
        lemma_step_valid_in_hnn(data, w1, step, next);
        lemma_derivation_valid_in_hnn(data, steps.drop_first(), next, w2);
    }
}

///  Base group embeds in HNN extension:
///  if w1 ≡ w2 in base, then w1 ≡ w2 in hnn_presentation.
pub proof fn lemma_base_embeds_in_hnn(data: HNNData, w1: Word, w2: Word)
    requires
        equiv_in_presentation(data.base, w1, w2),
    ensures
        equiv_in_presentation(hnn_presentation(data), w1, w2),
{
    let d = choose|d: Derivation| derivation_valid(data.base, d, w1, w2);
    lemma_derivation_valid_in_hnn(data, d.steps, w1, w2);
    let d_hnn = Derivation { steps: d.steps };
    assert(derivation_valid(hnn_presentation(data), d_hnn, w1, w2));
}

///  The HNN conjugation relation: t⁻¹·a_i·t ≡ b_i in the HNN presentation.
///  This is by construction: t⁻¹·a_i·t·b_i⁻¹ is a relator, so it equals ε,
///  hence t⁻¹·a_i·t ≡ b_i.
pub proof fn lemma_hnn_conjugation(data: HNNData, i: int)
    requires
        0 <= i < data.associations.len(),
        hnn_data_valid(data),
    ensures
        equiv_in_presentation(
            hnn_presentation(data),
            Seq::new(1, |_j: int| stable_letter_inv(data))
                + data.associations[i].0
                + Seq::new(1, |_j: int| stable_letter(data)),
            data.associations[i].1,
        ),
{
    reveal(presentation_valid);
    let hp = hnn_presentation(data);
    let bp = data.base;
    let (a_i, b_i) = data.associations[i];
    let t = stable_letter(data);
    let t_inv = stable_letter_inv(data);
    let lhs = Seq::new(1, |_j: int| t_inv) + a_i + Seq::new(1, |_j: int| t);

    let rel_idx = (bp.relators.len() + i) as nat;
    let relator = hnn_relator(data, i);
    assert(hp.relators[rel_idx as int] == relator);

    //  Step 1: relator ≡ ε (delete the relator)
    let step = DerivationStep::RelatorDelete {
        position: 0,
        relator_index: rel_idx,
        inverted: false,
    };
    assert(relator.subrange(0, 0int + relator.len() as int) =~= relator);
    let result = relator.subrange(0, 0int) + relator.subrange(0 + relator.len() as int, relator.len() as int);
    assert(result =~= empty_word());
    assert(apply_step(hp, relator, step) == Some(result));
    let d_del = Derivation { steps: Seq::new(1, |_j: int| step) };
    assert(d_del.steps.first() == step);
    assert(d_del.steps.drop_first() =~= Seq::<DerivationStep>::empty());
    assert(derivation_produces(hp, d_del.steps.drop_first(), result) == Some(result));
    assert(result == empty_word());
    assert(derivation_valid(hp, d_del, relator, empty_word()));
    //  relator ≡ ε

    assert(relator =~= concat(lhs, inverse_word(b_i)));

    //  concat(relator, b_i) ≡ b_i
    lemma_equiv_concat_left(hp, relator, empty_word(), b_i);
    assert(concat(empty_word(), b_i) =~= b_i);
    lemma_equiv_refl(hp, b_i);
    lemma_equiv_transitive(hp, concat(relator, b_i), concat(empty_word(), b_i), b_i);

    assert(concat(relator, b_i) =~= concat(lhs, concat(inverse_word(b_i), b_i)));

    //  inv(b_i) · b_i ≡ ε
    lemma_word_inverse_left(hp, b_i);

    //  lhs · (inv(b_i) · b_i) ≡ lhs · ε ≡ lhs
    lemma_equiv_concat_right(hp, lhs, concat(inverse_word(b_i), b_i), empty_word());
    assert(concat(lhs, empty_word()) =~= lhs);
    lemma_equiv_refl(hp, lhs);
    lemma_equiv_transitive(hp, concat(lhs, concat(inverse_word(b_i), b_i)), concat(lhs, empty_word()), lhs);

    //  Prove presentation_valid(hp) and word_valid for symmetric call
    let n = hp.num_generators;
    assert(n == bp.num_generators + 1);

    //  presentation_valid(hp)
    assert(presentation_valid(hp)) by {
        assert forall|k: int| 0 <= k < hp.relators.len()
            implies word_valid(hp.relators[k], hp.num_generators)
        by {
            if k < bp.relators.len() as int {
                //  base relator: word_valid for bp.num_generators < hp.num_generators
                assert(hp.relators[k] == bp.relators[k]);
                assert(word_valid(bp.relators[k], bp.num_generators));
                assert forall|m: int| 0 <= m < hp.relators[k].len()
                    implies symbol_valid(hp.relators[k][m], n) by {
                    assert(symbol_valid(hp.relators[k][m], bp.num_generators));
                }
            } else {
                //  HNN relator at index bp.relators.len() + j
                let j = k - bp.relators.len() as int;
                let hr = hnn_relator(data, j);
                assert(hp.relators[k] == hr);
                let (aj, bj) = data.associations[j];
                //  hr = t_inv ++ aj ++ t ++ inv(bj)
                //  All symbols valid for n = bp.num_generators + 1
                assert(word_valid(aj, bp.num_generators));
                crate::word::lemma_inverse_word_valid(bj, bp.num_generators);
                assert forall|m: int| 0 <= m < hr.len()
                    implies symbol_valid(hr[m], n) by {
                    //  manual: check each segment of the HNN relator
                    let t_inv_w = Seq::new(1, |_j2: int| t_inv);
                    let t_w = Seq::new(1, |_j2: int| t);
                    let inv_bj = inverse_word(bj);
                    //  hr = t_inv_w + aj + t_w + inv_bj
                    if m < 1 {
                        //  t_inv = Inv(bp.num_generators), valid for n
                        assert(hr[m] == t_inv);
                    } else if m < (1 + aj.len()) as int {
                        assert(hr[m] == aj[(m - 1) as int]);
                        assert(symbol_valid(aj[(m - 1) as int], bp.num_generators));
                    } else if m < (2 + aj.len()) as int {
                        assert(hr[m] == t);
                    } else {
                        let inv_idx = (m - 2 - aj.len()) as int;
                        assert(hr[m] == inv_bj[inv_idx]);
                        assert(symbol_valid(inv_bj[inv_idx], bp.num_generators));
                    }
                }
            }
        }
    }

    //  word_valid for concat(lhs, concat(inv(b_i), b_i))
    assert(word_valid(b_i, n)) by {
        assert(word_valid(b_i, bp.num_generators));
        assert forall|m: int| 0 <= m < b_i.len() implies symbol_valid(b_i[m], n) by {
            assert(symbol_valid(b_i[m], bp.num_generators));
        }
    }
    crate::word::lemma_inverse_word_valid(b_i, n);
    crate::word::lemma_concat_word_valid(inverse_word(b_i), b_i, n);

    assert(word_valid(a_i, n)) by {
        assert(word_valid(a_i, bp.num_generators));
        assert forall|m: int| 0 <= m < a_i.len() implies symbol_valid(a_i[m], n) by {
            assert(symbol_valid(a_i[m], bp.num_generators));
        }
    }
    assert(word_valid(lhs, n)) by {
        assert forall|m: int| 0 <= m < lhs.len() implies symbol_valid(lhs[m], n) by {
            let t_inv_w = Seq::new(1, |_j2: int| t_inv);
            let t_w = Seq::new(1, |_j2: int| t);
            if m < 1 {
                assert(lhs[m] == t_inv);
            } else if m < (1 + a_i.len()) as int {
                assert(lhs[m] == a_i[(m - 1) as int]);
            } else {
                assert(lhs[m] == t);
            }
        }
    }
    crate::word::lemma_concat_word_valid(lhs, concat(inverse_word(b_i), b_i), n);

    //  symmetric: lhs ≡ concat(lhs, concat(inv(b_i), b_i))
    lemma_equiv_symmetric(hp, concat(lhs, concat(inverse_word(b_i), b_i)), lhs);
    //  chain: lhs ≡ concat(relator, b_i) ≡ b_i
    lemma_equiv_transitive(hp, lhs, concat(lhs, concat(inverse_word(b_i), b_i)), b_i);
}

///  The i-th HNN relator has the expected structure: t⁻¹·a_i·t·b_i⁻¹.
pub proof fn lemma_hnn_relator_structure(data: HNNData, i: int)
    requires
        0 <= i < data.associations.len(),
    ensures ({
        let hp = hnn_presentation(data);
        let bp = data.base;
        let rel_idx = bp.relators.len() + i;
        let (a_i, b_i) = data.associations[i];
        let t = stable_letter(data);
        let t_inv = stable_letter_inv(data);
        hp.relators[rel_idx] == Seq::new(1, |_j: int| t_inv) + a_i + Seq::new(1, |_j: int| t) + inverse_word(b_i)
    }),
{
    let hp = hnn_presentation(data);
    let bp = data.base;
    let rel_idx = (bp.relators.len() + i) as int;
    assert(hp.relators[rel_idx] == hnn_relator(data, i));
}

} //  verus!
